defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:14-browsers

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: npm t
      - run:
          name: Check syntax
          command: npm run lint
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Add publish token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish
          command: npx @lets/publish

workflows:
  version: 2.1
  release:
    jobs:
      - test
      - publish:
          context: globalenv
          requires:
            - test
          filters:
            branches:
              only:
                - master
